### ISSUE TITLE
Duplicate strdup symbol

### ISSUE THREAD

**Issue by schwehr** [HDFGroup/hdf4#446]
I'm hitting an error with some sanitizer builds with the 2nd strdup in hdf4 caused by #442 that did `HDstrdup` → `strdup` in hdfalloc.c

https://github.com/HDFGroup/hdf4/blob/7cbfa6f279f65dede5dbd8bd787d93239c0e2741/hdf/src/hdfalloc.c#L141

```
backward reference detected: strdup in third_party/gdal/_objs/port_lib/json_object.pic.o refers to third_party/hdf4/_objs/libdf/hdfalloc.pic.o
```

**Comment by derobins** [comment]
I'll remove that duplicate symbol. I didn't even know that existed. I'll probably also replace HIstrncpy (in a separate PR) while I'm at it.

**Comment by schwehr** [comment]
Also here: https://github.com/HDFGroup/hdf4/blob/bb23516f05e764db2e8eeec59a429f1180bbe309/hdf/src/hproto.h#L327
