### PR TITLE
Fix H4_DFI_H endif.

### PR DESCRIPTION
**Pull request by sebastic**
NCL failed to build with hdf4 4.2.16:
```
/usr/include/hdf/dfi.h:128:2: error: #endif without #if
  128 | #endif /* H4_DFI_H */
      |  ^~~~~
```
When the `endif` for `APOLLO` is removed to not close `#ifndef H4_DFI_H` too soon a different error occurs:
```
 /usr/include/hdf/dfi.h:53:33: error: two or more data types in declaration specifiers
    53 | #define float32                 float
       |                                 ^~~~~
 /usr/include/hdf/hdfi.h:121:16: note: in expansion of macro 'float32'
   121 | typedef float  float32;
       |                ^~~~~~~
 /usr/include/hdf/hdfi.h:121:1: warning: useless type name in empty declaration
   121 | typedef float  float32;
       | ^~~~~~~
```
Re-instating `#ifdef APOLLO` resolves the issue.

### CODE REVIEW

**Review by hyoklee — APPROVED** [review]
Thank you for your PR!

**Comment by bmribler** [comment]
I think PR# 98 meant to remove the entire #ifdef APOLLO block but missed the matching #endif.

**Comment by sebastic** [comment]
> I think PR# 98 meant to remove the entire #ifdef APOLLO block but missed the matching #endif.

Thanks sounds very plausible, removing the entire block may be a better fix that my single line change.

**Comment by derobins** [comment]
> > I think PR# 98 meant to remove the entire #ifdef APOLLO block but missed the matching #endif.
> 
> Thanks sounds very plausible, removing the entire block may be a better fix that my single line change.

Yes. That was a mistake on my part. Good catch! Thanks!

If you could remove the entire block, down to 'endif /*APOLLO */' around line 93, that would be better and we can get that in right away.

**Review by derobins — APPROVED** [review]

**Comment by derobins** [comment]
Looks like codespell updated. I'll fix that ASAP.

**Review by bmribler — APPROVED** [review]
